resources:
- manifests.yaml
- service.yaml

configurations:
- kustomizeconfig.yaml

patches:
  - target:
      group: admissionregistration.k8s.io
      version: v1
    patch: |
      - op: add
        path: "/webhooks/0/namespaceSelector"
        value:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - gomenhashai-system
                - kube-system
