{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kintegrity.fullname" . }}-manager-role
  labels:
  {{- include "kintegrity.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - update
  - watch
  - patch
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kintegrity.fullname" . }}-manager-rolebinding
  labels:
  {{- include "kintegrity.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "kintegrity.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "kintegrity.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
{{- end }}
