apiVersion: v1
kind: Service
metadata:
  name: {{ include "kintegrity.fullname" . }}-metrics-service
  labels:
    {{- include "kintegrity.labels" . | nindent 4 }}
    {{- with .Values.metrics.service.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  selector:
    app.kubernetes.io/name: kintegrity
    {{- include "kintegrity.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.metrics.service.port }}
      protocol: TCP
      targetPort: {{ .Values.metrics.service.targetPort }}
