{{- if not (or (index .Values "certificates" "cert-manager" "enabled") .Values.certificates.webhook.secretName .Values.certificates.metrics.secretName) }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "gomenhashai.metricsSecretName" . }}
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
data:
  ca.crt: {{ include "gomenhashai.ca" . | b64enc }}
  tls.crt: {{ index (include "gomenhashai.metricscert" .) "Cert" | b64enc }}
  tls.key: {{ index (include "gomenhashai.metricscert" .) "Key" | b64enc }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "gomenhashai.webhookSecretName" . }}
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
data:
  ca.crt: {{ include "gomenhashai.ca" . | b64enc }}
  tls.crt: {{ index (include "gomenhashai.webhookcert" .) "Cert" | b64enc }}
  tls.key: {{ index (include "gomenhashai.webhookcert" .) "Key" | b64enc }}
{{- end }}
