{{- if not (or (index .Values "certificates" "cert-manager" "enabled") .Values.certificates.webhook.secretName .Values.certificates.metrics.secretName) }}
{{- $ca := genCA "gomenhashai-ca" (int .Values.certificates.duration) -}}
{{- $crt := genSignedCert "gomenhashai-metrics-cert" nil (list (printf "%s-metrics-service.%s.svc" (include "gomenhashai.fullname" .) .Release.Namespace) (printf "%s-metrics-service.%s.svc.%s" (include "gomenhashai.fullname" .) .Release.Namespace .Values.kubernetesClusterDomain)) (int .Values.certificates.duration) $ca -}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "gomenhashai.metricsSecretName" . }}
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $crt.Cert | b64enc }}
  tls.key: {{ $crt.Key | b64enc }}
{{- end }}
