{{- if and (index .Values "certificates" "cert-manager" "enabled") (index .Values "certificates" "cert-manager" "create") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gomenhashai.metricsSecretName" . }}
  labels:
  {{- include "gomenhashai.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "gomenhashai.fullname" . }}-metrics-service.{{ .Release.Namespace }}.svc'
  - '{{ include "gomenhashai.fullname" . }}-metrics-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    {{- if index .Values "certificates" "cert-manager" "issuer" }}
    name: {{ index .Values "certificates" "cert-manager" "issuer" }}
    {{- else }}
    name: '{{ include "gomenhashai.fullname" . }}-selfsigned-issuer'
    {{- end }}
  secretName: {{ include "gomenhashai.metricsSecretName" . }}
{{- end }}
