{{- if and (index .Values "certificates" "cert-manager" "enabled") (index .Values "certificates" "cert-manager" "create") (not (index .Values "certificates" "cert-manager" "issuer")) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "gomenhashai.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "gomenhashai.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
