{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gomenhashai.fullname" . }}-config
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- toYaml .Values.config | nindent 4 }}
{{- end }}