{{- $ca := genCA "gomenhashai-ca" (int .Values.certificates.duration) -}}
{{- $crt := genSignedCert "gomenhashai-webhook-cert" nil (list (printf "%s-webhook-service.%s.svc" (include "gomenhashai.fullname" .) .Release.Namespace) (printf "%s-webhook-service.%s.svc.%s" (include "gomenhashai.fullname" .) .Release.Namespace .Values.kubernetesClusterDomain)) (int .Values.certificates.duration) $ca -}}
{{- if not (or (index .Values "certificates" "cert-manager" "enabled") .Values.certificates.webhook.secretName .Values.certificates.metrics.secretName) }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "gomenhashai.webhookSecretName" . }}
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $crt.Cert | b64enc }}
  tls.key: {{ $crt.Key | b64enc }}
{{- end }}
{{- if .Values.webhook.validating.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "gomenhashai.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
    {{- with .Values.webhook.validating.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if index .Values "certificates" "cert-manager" "enabled" }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "gomenhashai.webhookSecretName" . }}
    {{- end }}
    {{- with .Values.webhook.validating.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if .Values.webhook.validating.caBundle }}
    caBundle: {{ .Values.webhook.validating.caBundle | b64enc }}
    {{- else }}
    {{- if not (or (index .Values "certificates" "cert-manager" "enabled") .Values.certificates.webhook.secretName .Values.certificates.metrics.secretName) }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    {{- end }}
    service:
      name: '{{ include "gomenhashai.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate--v1-pod
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  matchPolicy: {{ .Values.webhook.validating.matchPolicy }}
  name: vpod-v1.kb.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - {{ .Release.Namespace }}
    {{- range $key, $value := .Values.webhook.validating.exemptNamespacesLabels }}
    - key: {{ $key }}
      operator: NotIn
      values:
      {{- range $value }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- with .Values.webhook.validating.objectSelector }}
  objectSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: {{ .Values.webhook.validating.sideEffects }}
{{- end }}
{{- if .Values.webhook.mutating.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "gomenhashai.fullname" . }}-mutating-webhook-configuration
  labels:
    {{- include "gomenhashai.labels" . | nindent 4 }}
    {{- with .Values.webhook.mutating.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if index .Values "certificates" "cert-manager" "enabled" }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "gomenhashai.webhookSecretName" . }}
    {{- end }}
    {{- with .Values.webhook.mutating.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if .Values.webhook.mutating.caBundle }}
    caBundle: {{ .Values.webhook.mutating.caBundle | b64enc }}
    {{- else }}
    {{- if not (or (index .Values "certificates" "cert-manager" "enabled") .Values.certificates.webhook.secretName .Values.certificates.metrics.secretName) }}
    caBundle: {{ $ca.Cert | b64enc }}
    {{- end }}
    {{- end }}
    service:
      name: '{{ include "gomenhashai.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate--v1-pod
  failurePolicy: {{ .Values.webhook.mutating.failurePolicy }}
  matchPolicy: {{ .Values.webhook.mutating.matchPolicy }}
  reinvocationPolicy: {{ .Values.webhook.mutating.reinvocationPolicy }}
  name: mpod-v1.kb.io
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - {{ .Release.Namespace }}
    {{- range $key, $value := .Values.webhook.mutating.exemptNamespacesLabels }}
    - key: {{ $key }}
      operator: NotIn
      values:
      {{- range $value }}
      - {{ . }}
      {{- end }}
    {{- end }}
  {{- with .Values.webhook.mutating.objectSelector }}
  objectSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: {{ .Values.webhook.mutating.sideEffects }}
{{- end }}
